// This file was generated by Prisma, and assumes you have installed the following:
// npm install --save-dev prisma dotenv
import "dotenv/config";
import fs from "fs";
import path from "path";
import { defineConfig } from "prisma/config";

try {
  const schemaPath = path.resolve(__dirname, "prisma/schema.prisma");
  if (fs.existsSync(schemaPath)) {
    let schema = fs.readFileSync(schemaPath, "utf8");
    const dbUrl = process.env.DATABASE_URL || "";
    const isPostgres = dbUrl.startsWith("postgres://") || dbUrl.startsWith("postgresql://") || dbUrl.startsWith("prisma://") || dbUrl.startsWith("neon://");
    const targetProvider = isPostgres ? "postgresql" : "sqlite";
    schema = schema.replace(/provider\s*=\s*"(sqlite|postgresql)"/, `provider = "${targetProvider}"`);
    fs.writeFileSync(schemaPath, schema);
  }
} catch (e) {
  console.error("Could not auto-sync schema provider:", e);
}

export default defineConfig({
  schema: "prisma/schema.prisma",
  migrations: {
    path: "prisma/migrations",
  },
  datasource: {
    url: process.env["DATABASE_URL"],
  },
});
