// This file was generated by Prisma, and assumes you have installed the following:
// npm install --save-dev prisma dotenv
import "dotenv/config";
import fs from "fs";
import path from "path";
import { defineConfig } from "prisma/config";

try {
  const schemaPath = path.resolve(__dirname, "prisma/schema.prisma");
  if (fs.existsSync(schemaPath)) {
    let schema = fs.readFileSync(schemaPath, "utf8");
    const dbUrl = (process.env.DATABASE_URL || "").trim();
    const lowerUrl = dbUrl.toLowerCase();
    const isPostgres =
      lowerUrl.startsWith("postgres://") ||
      lowerUrl.startsWith("postgresql://") ||
      lowerUrl.startsWith("jdbc:postgresql://") ||
      lowerUrl.startsWith("prisma://") ||
      lowerUrl.startsWith("neon://") ||
      lowerUrl.includes("aivencloud") ||
      lowerUrl.includes("neondb") ||
      lowerUrl.includes("supabase") ||
      lowerUrl.includes("sslmode=") ||
      (lowerUrl.includes("@") && !lowerUrl.startsWith("file:"));
    const targetProvider = isPostgres ? "postgresql" : "sqlite";
    schema = schema.replace(/provider\s*=\s*"(sqlite|postgresql)"/, `provider = "${targetProvider}"`);
    fs.writeFileSync(schemaPath, schema);
  }
} catch (e) {
  console.error("Could not auto-sync schema provider:", e);
}

export default defineConfig({
  schema: "prisma/schema.prisma",
  migrations: {
    path: "prisma/migrations",
  },
  datasource: {
    url: process.env["DATABASE_URL"],
  },
});
